// Noah/bench/report.cjs
//
// Turns the raw JSON written by the harness into Noah/docs/BENCHMARKS.md.
// It only re-formats recorded results; it never invents a number. Run:
//
//   node Noah/bench/report.cjs
//
// Inputs : Noah/bench/results/bench-*.json (harness runs) and integration-app.json
// Output : Noah/docs/BENCHMARKS.md

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..", "..");
const RES = path.join(ROOT, "Noah", "bench", "results");
const OUT = path.join(ROOT, "Noah", "docs", "BENCHMARKS.md");

const runs = fs
  .readdirSync(RES)
  .filter((f) => /^bench-.*\.json$/.test(f))
  .sort()
  .map((f) => ({ file: f, ...JSON.parse(fs.readFileSync(path.join(RES, f), "utf8")) }));
if (!runs.length) {
  console.error("no bench-*.json results found - run the harness first (see docs/ARCHITECTURE.md)");
  process.exit(1);
}
const integrationFile = path.join(RES, "integration-app.json");
const integration = fs.existsSync(integrationFile) ? JSON.parse(fs.readFileSync(integrationFile, "utf8")) : null;

const label = (r) => `DPR ${r.meta.dpr === "system" ? "1 (system)" : r.meta.dpr} / zoom ${r.meta.zoom}`;
const pct = (n, d) => (d ? `${Math.round((n / d) * 1000) / 10}%` : "n/a");
const lines = [];
const out = (s = "") => lines.push(s);

out("# Noah benchmark results");
out();
out(`Generated by \`node Noah/bench/report.cjs\` from the raw JSON in \`Noah/bench/results/\`. Nothing here is hand-edited.`);
out();
out("## What these numbers are (and are not)");
out();
out("| Tier | What runs | What it proves | What it does NOT prove |");
out("|---|---|---|---|");
out("| **A** | Deterministic scenarios that drive the real controllers (perception, coordinate mapping, CDP mouse/keyboard, verification, safety) in a real Electron `<webview>`. **No model.** | The hands and eyes work: clicks land where intended at DPR/zoom variants, canvases, iframes, drag-and-drop, dialogs, uploads, injection defenses, emergency stop, takeover. | Anything about model quality. |");
out("| **B** | The real `NoahAgent` loop (observe → decide → act → verify → recover, budgets, checkpoints, routing, failover, confirmation flow) driven by a **scripted reference policy** standing in for the model. **It is not an LLM.** | The orchestration, recovery ladder, safety gating and bookkeeping behave as designed. | That any real LLM will pick these actions. **No real-LLM success rate exists in this repository.** |");
out("| **Integration** | The real Jonah app (`main.cjs` + `index.html`), a legacy Rexy goal routed into Noah, the real `OpenAIProvider` over HTTP to a local scripted server. | The wiring in the shipped app: preload, IPC, tab bridge, overlay, legacy event relay, no CDP debugger left attached. | Live cloud endpoints or model behaviour. |");
out();

out("## Harness runs");
out();
out("| Run | Electron / Chromium | Scenarios | Passed | Failed | Success | Avg scenario | CDP calls |");
out("|---|---|---|---|---|---|---|---|");
for (const r of runs) {
  const s = r.summary;
  out(`| ${label(r)} | ${r.meta.electron} / ${r.meta.chromium} | ${s.total} | ${s.passed} | ${s.failed} | ${s.successRate}% | ${s.avgScenarioMs} ms | ${s.totalCdpCalls} |`);
}
out();
out(`Recorded ${runs.map((r) => r.meta.when).sort()[0]} → ${runs.map((r) => r.meta.when).sort().slice(-1)[0]} on ${runs[0].meta.platform}.`);
out();

// ------------------------------------------------------------------ by category
const cats = [...new Set(runs.flatMap((r) => Object.keys(r.summary.byCategory)))];
out("## Success by category");
out();
out(`| Category | ${runs.map(label).join(" | ")} |`);
out(`|---|${runs.map(() => "---").join("|")}|`);
for (const c of cats) {
  out(`| ${c} | ${runs.map((r) => { const v = r.summary.byCategory[c]; return v ? `${v.passed}/${v.total}` : "-"; }).join(" | ")} |`);
}
out();

// ------------------------------------------------------------------ scenarios
const base = runs[0];
out("## Every scenario");
out();
out(`| ID | Tier | Category | Scenario | ${runs.map(label).join(" | ")} |`);
out(`|---|---|---|---|${runs.map(() => "---").join("|")}|`);
for (const s of base.results) {
  const cells = runs.map((r) => {
    const m = r.results.find((x) => x.id === s.id);
    return m ? `${m.pass ? "pass" : "**FAIL**"} (${m.durationMs} ms)` : "-";
  });
  out(`| ${s.id} | ${s.tier} | ${s.category} | ${s.name.replace(/\|/g, "/")} | ${cells.join(" | ")} |`);
}
out();

const failures = runs.flatMap((r) => r.results.filter((x) => !x.pass).map((x) => ({ run: label(r), ...x })));
out("## Failures");
out();
if (!failures.length) out("None in the recorded runs.");
for (const f of failures) out(`- **${f.id}** (${f.run}): ${f.details}`);
out();

// ------------------------------------------------------------------ tier B metrics
const tierB = base.results.filter((r) => r.tier === "B");
if (tierB.length) {
  out("## Tier B agent-loop metrics (scripted policy, not an LLM)");
  out();
  out("Per scenario, from the first run above. `obs tokens` is an estimate (chars / 3.6 + 1000 per image), not a billed count; `model calls` counts the scripted provider's calls including the planner.");
  out();
  out("| ID | Scenario | Result | Steps | Actions | Failures | Recovery ladders | Model calls | Screenshots | Est. obs tokens | Elapsed |");
  out("|---|---|---|---|---|---|---|---|---|---|---|");
  for (const r of tierB) {
    const m = r.metrics || {};
    const cell = (v) => (v === undefined || v === null ? "-" : v);
    out(`| ${r.id} | ${r.name.replace(/\|/g, "/")} | ${r.pass ? "pass" : "**FAIL**"} | ${cell(m.steps)} | ${cell(m.actions)} | ${cell(m.actionFailures)} | ${cell(m.laddersUsed)} | ${cell(m.modelCalls)} | ${cell(m.screenshots)} | ${cell(m.obsTokensEst)} | ${m.elapsedMs !== undefined ? m.elapsedMs + " ms" : r.durationMs + " ms"} |`);
  }
  out();
}

// ------------------------------------------------------------------ CDP method mix
if (base.cdpMethods) {
  const top = Object.entries(base.cdpMethods).sort((a, b) => b[1] - a[1]).slice(0, 12);
  out("## CDP method mix (first run)");
  out();
  out("| Method | Calls |");
  out("|---|---|");
  for (const [m, n] of top) out(`| \`${m}\` | ${n} |`);
  out();
}

// ------------------------------------------------------------------ integration
if (integration) {
  out("## Real-app integration");
  out();
  out(`${integration.summary.passed}/${integration.summary.total} checks passed (Electron ${integration.electron}, ${integration.when}). ${integration.note}.`);
  out();
  out("| Check | Result | Detail |");
  out("|---|---|---|");
  for (const c of integration.checks) out(`| ${c.name.replace(/\|/g, "/")} | ${c.ok ? "pass" : "**FAIL**"} | ${String(c.detail || "").replace(/\|/g, "/").slice(0, 160)} |`);
  out();
  out("Evidence images: `Noah/bench/results/integration-purple-cursor.png` (full shell) and `integration-purple-cursor-zoom.png` (4x crop of the cursor). The check above counts solid `#7C3AED` pixels in the captured frame rather than trusting DOM state.");
  out();
}

// ------------------------------------------------------------------ live agent-session runs (real model, real sites)
for (const scenario of ["main", "error"]) {
  const file = path.join(RES, `session-run-${scenario}.json`);
  if (!fs.existsSync(file)) continue;
  const sr = JSON.parse(fs.readFileSync(file, "utf8"));
  const passed = sr.results.filter((r) => r.pass).length;
  out(`## Live agent-session run (${scenario === "main" ? "one app session, instructions A-G and T" : "the model is unreachable"})`);
  out();
  out(`${passed}/${sr.results.length} checks passed (${sr.when}). ${sr.note}.`);
  out();
  out("| Check | Result | Detail |");
  out("|---|---|---|");
  for (const c of sr.results) out(`| ${c.id}: ${c.name.replace(/\|/g, "/")} | ${c.pass ? "pass" : "**FAIL**"} | ${String(c.detail || "").replace(/\|/g, "/").replace(/\n/g, " ").slice(0, 140)}${c.machineInputDuringRun ? " (physical mouse movement detected during this run)" : ""} |`);
  out();
  if (sr.runs && sr.runs.length) {
    out("| Run | Instruction | Source | Outcome | Seconds | Status updates shown | Steps | Model calls | Local steps | Timeouts |");
    out("|---|---|---|---|---|---|---|---|---|---|");
    for (const r of sr.runs) out(`| ${r.id} | ${String(r.text).replace(/\|/g, "/").slice(0, 60)} | ${r.source} | ${r.status} | ${r.seconds} | ${r.statusUpdates} | ${r.steps ?? ""} | ${r.modelCalls ?? ""} | ${r.localSteps ?? ""} | ${r.timeouts ?? ""} |`);
    out();
    out("Model calls are real round trips to the hosted model; local steps are steps the adapter worked out itself (typing a script, scrolling, waiting), which older builds also counted as model calls.");
    out();
  }
}

fs.writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`wrote ${path.relative(ROOT, OUT)} (${runs.length} runs, ${base.results.length} scenarios)`);
