name: Build & Publish Jonah

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
